[package]
name = "root_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }